### ISSUE TITLE
Showing only one variant, every-time refreshed

### ISSUE THREAD

**Issue by khanharis87** [marvelapp/react-ab-test#20]
<h1>Table of Contents</h1>

- [Expected Behavior](#expected-behavior)
- [Current Behavior](#current-behavior)
- [Possible Solution](#possible-solution)
- [Steps to Reproduce (for bugs)](#steps-to-reproduce-for-bugs)
- [Context](#context)
- [Your Environment](#your-environment)

## Expected Behavior
 show 50, 50 of 2 variants as assigned in defineVariants

```
emitter.defineVariants(
  "themeExperiment",
  ["darkTheme", "lightTheme"],
  [50, 50]
);

const Pride: React.SFC = () => {
  return (
    <Experiment name="themeExperiment">
      <Variant name="darkTheme">
        <DarkTheme />
      </Variant>
      <Variant name="lightTheme">
        <LightTheme />
      </Variant>
    </Experiment>
  );
};
```
## Current Behavior
Only one variant being shown

## Possible Solution
My console cries about using old react lifecycle methods.

## Steps to Reproduce (for bugs)
Use one the examples and it does the same, after refreshing few times, it still shows same variant

## Your Environment

* Version used: ^2.3.0
* Browser Name and version: Chrome Version 84.0.4147.105 
* Operating System and version (desktop or mobile): both
* Framework: Next.js version 9

**Comment by moretti** [comment]
@khanharis87 It's because the active variant is saved on local storage (see [`calculateActiveVariant`](https://github.com/marvelapp/react-ab-test/blob/master/src/calculateActiveVariant.jsx#L60) and [`store`](https://github.com/marvelapp/react-ab-test/blob/master/src/store.jsx)).

It is done on purpose, ideally a user should always get the same variant and this is best thing that we can do client-side.

If you delete `PUSHTELL-${experimentName}` from local storage and refresh the page, `react-ab-test` will pick another variant (see https://developers.google.com/web/tools/chrome-devtools/storage/localstorage).

**Comment by khanharis87** [comment]
Thanks for the reply, It makes sense, but before( last week) it was showing different variants on refresh. So that is why I am confused

**Comment by moretti** [comment]
@khanharis87 it might be because you used a different browser, cleared the browsing data or, in case of local development used a different address or port number, (e.g. `localhost:1234` vs `localhost:5678` or `127.0.0.1` vs `localhost`).
